<?php

namespace Database\Seeders;
use DB; // これがないとエラーになる。注意
use Illuminate\Database\Seeder;

class MoviesTableSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::table('movies')->insert(
			[
				[
					'title'=>'すごい映画1',
					'image_url'=>'https://picsum.photos/100',
					'published_year'=>'2021',
					'is_showing'=>0,
					'description'=>'なんかすごくてすごい映画'
				],
				[
					'title'=>'すごい映画2',
					'image_url'=>'https://picsum.photos/100',
					'published_year'=>'2020',
					'is_showing'=>1,
					'description'=>'なんかすごくてすごい映画'
				],
				[
					'title'=>'すごい映画3',
					'image_url'=>'https://picsum.photos/100',
					'published_year'=>'2019',
					'is_showing'=>0,
					'description'=>'なんかすごくてすごい映画'
				],
				[
					'title'=>'すごい映画4',
					'image_url'=>'https://picsum.photos/100',
					'published_year'=>'2018',
					'is_showing'=>1,
					'description'=>'なんかすごくてすごい映画'
				],
				[
					'title'=>'すごい映画5',
					'image_url'=>'https://picsum.photos/100',
					'published_year'=>'2017',
					'is_showing'=>0,
					'description'=>'なんかすごくてすごい映画'
				],
				[
					'title'=>'すごい映画6',
					'image_url'=>'https://picsum.photos/100',
					'published_year'=>'2016',
					'is_showing'=>1,
					'description'=>'なんかすごくてすごい映画'
				],
				[
					'title'=>'すごい映画7',
					'image_url'=>'https://picsum.photos/100',
					'published_year'=>'2015',
					'is_showing'=>0,
					'description'=>'なんかすごくてすごい映画'
				],
				[
					'title'=>'すごい映画8',
					'image_url'=>'https://picsum.photos/100',
					'published_year'=>'2014',
					'is_showing'=>1,
					'description'=>'なんかすごくてすごい映画'
				],
				[
					'title'=>'すごい映画9',
					'image_url'=>'https://picsum.photos/100',
					'published_year'=>'2013',
					'is_showing'=>0,
					'description'=>'なんかすごくてすごい映画'
				],
				[
					'title'=>'すごい映画10',
					'image_url'=>'https://picsum.photos/100',
					'published_year'=>'2012',
					'is_showing'=>1,
					'description'=>'なんかすごくてすごい映画'
				],
				[
					'title'=>'すごい映画11',
					'image_url'=>'https://picsum.photos/100',
					'published_year'=>'2011',
					'is_showing'=>0,
					'description'=>'なんかすごくてすごい映画'
				],
				[
					'title'=>'すごい映画12',
					'image_url'=>'https://picsum.photos/100',
					'published_year'=>'2010',
					'is_showing'=>1,
					'description'=>'なんかすごくてすごい映画'
				],
				[
					'title'=>'すごい映画13',
					'image_url'=>'https://picsum.photos/100',
					'published_year'=>'2009',
					'is_showing'=>0,
					'description'=>'なんかすごくてすごい映画'
				],
				[
					'title'=>'すごい映画14',
					'image_url'=>'https://picsum.photos/100',
					'published_year'=>'2008',
					'is_showing'=>1,
					'description'=>'なんかすごくてすごい映画'
				],
				[
					'title'=>'すごい映画15',
					'image_url'=>'https://picsum.photos/100',
					'published_year'=>'2007',
					'is_showing'=>0,
					'description'=>'なんかすごくてすごい映画'
				],
				[
					'title'=>'すごい映画16',
					'image_url'=>'https://picsum.photos/100',
					'published_year'=>'2006',
					'is_showing'=>1,
					'description'=>'なんかすごくてすごい映画'
				],
				[
					'title'=>'すごい映画17',
					'image_url'=>'https://picsum.photos/100',
					'published_year'=>'2005',
					'is_showing'=>0,
					'description'=>'なんかすごくてすごい映画'
				],[
					'title'=>'すごい映画18',
					'image_url'=>'https://picsum.photos/100',
					'published_year'=>'2004',
					'is_showing'=>1,
					'description'=>'なんかすごくてすごい映画'
				],
			]
		);
	}
}
